branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

environment:

  global:
    PIP_CACHE_DIR: "pip_cache"

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "64"
      TOXENV: py27
      CONDA: true

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      TOXENV: py35
      CONDA: true

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      TOXENV: py36
      CONDA: true

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "64"
      TOXENV: py27

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.5"
      PYTHON_ARCH: "64"
      TOXENV: py34

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      TOXENV: py35

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      TOXENV: py36

matrix:
  fast_finish: true

clone_depth: 2

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%bit"

cache:
    - pip_cache -> appveyor.yml


install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: |
      if ($env:CONDA -eq "true") {
          conda config --set always_yes yes --set changeps1 no;
          conda install -q pip setuptools wheel tox scipy
      } else {
          python -m pip install pip setuptools wheel tox --upgrade
      }

build: off

test_script:
  - tox
